### ISSUE TITLE
Add Winner/Loser phase

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/war_masters#23]
A phase after the battle that shows who won and who lost, use flavour text like 'These players won the battle'

Opened from Discord by **darklord#1296**
Follow the conversation [here](https://discord.com/channels/501306949434867713/769109626020298784/839785896844066847)

**Comment by fcalife** [comment]
its called a results phase

show bets per player

show winners

show how much gold each winner gained

**Comment by TideSofDarK** [comment]
![изображение](https://user-images.githubusercontent.com/1160901/117545085-c1738880-b03d-11eb-8c26-1e7270b03177.png)
