### ISSUE TITLE
First two battles should be hand crafted to act as tutorial and to be non confusing

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/war_masters#40]
Two battles are hand crafted as described below

Opened from Discord by **darklord#1296**
Follow the conversation [here](https://discord.com/channels/501306949434867713/769109626020298784/840846506970054709)

**Comment by fcalife** [comment]
Battle #1:

- a single, random large unit

versus

- a single, random large unit (different from the first one)

**Comment by fcalife** [comment]
Battle #2:

- a single, random large unit
- a normal spawn amount of a random fodder unit

versus

- a single, random large unit (different from the first one)
- the same random fodder unit (also normal spawn amount) from the other army
